baseurl = "/"
languageCode = "en-us"
title = "Erik Ø. Sørensen - Statsøkonomen"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Erik Ø. Sørensen"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "CV"
    url = "/erik-o-sorensen-cv/"
    weight = 20

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ErikOSorensen"
    weight = 40
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ErikOSorensen"
    weight = 30
[[menu.main]]
    name = "ORCiD"
    url = "https://orcid.org/0000-0002-7155-4188"
    weight = 25
[[menu.main]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=vV3i8C3IPygC&hl=en"
    weight = 50
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "Statsokonomen.ico"

    [params.logo]
    url = "Statsokonomen.png"
    width = 50
    height = 50
    alt = "Logo"

